import unittest
import heapq
from typing import List, Tuple
from ideal_completion import (
    EnvAgent, Directions, GridTransitionMap, bunny_heuristic, sipp,
    handle_movement_sipp, is_conflict, relaxed_planning, 
    execute_with_relaxed_planning
)

class TestPathPlanning(unittest.TestCase):

    def setUp(self):
        # Setting up mock agents and environment parameters to be used in the tests.
        self.agents = [
            EnvAgent(initial_position=(0, 0), initial_direction=Directions.EAST, target=(5, 5)),
            EnvAgent(initial_position=(1, 1), initial_direction=Directions.SOUTH, target=(4, 4)),
        ]
        # 6x6 grid environment
        self.grid_size = (6, 6)
        self.rail = GridTransitionMap(self.grid_size)
        self.max_timestep = 10
        self.initial_planning_fraction = 0.5

    def test_bunny_heuristic(self):
        # Verifies that the heuristic function returns the correct Manhattan distance between two points.
        # The heuristic is critical in pathfinding algorithms like A* and SIPP because it helps estimate the remaining distance to the target.
        self.assertEqual(bunny_heuristic(None, (0, 0), (5, 5)), 10)  # Expected distance is 10 (|5-0| + |5-0|)
        self.assertEqual(bunny_heuristic(None, (1, 1), (4, 4)), 6)   # Expected distance is 6 (|4-1| + |4-1|)

    def test_get_transitions(self):
        # Tests if the grid transition map correctly identifies valid directions an agent can move from a given position.
        # Ensures that the environment's rules regarding movement constraints are properly implemented, which is vital for valid pathfinding.
        transitions = self.rail.get_transitions(0, 0, Directions.NORTH)
        self.assertEqual(transitions, [False, True, True, False])  # Can move EAST, SOUTH from (0,0)
        
        transitions = self.rail.get_transitions(5, 5, Directions.SOUTH)
        self.assertEqual(transitions, [True, False, False, True])  # Can move NORTH, WEST from (5,5)

    def test_is_conflict(self):
        # Verifies if the conflict detection logic is working when checking if two paths collide at any point.
        # This is crucial to ensure that multiple agents avoid colliding or "swapping" positions during the same timestep.
        existing_paths = [[(0, 0), (0, 1)], [(1, 1), (1, 2)]]
        
        # No conflict as Agent 1 is far from Agent 2's path
        no_conflict = is_conflict((1, 3), 2, (1, 2), 1, existing_paths)
        self.assertFalse(no_conflict)

        # A conflict is expected as Agent 0 and Agent 1 would both be in (0,1) at the same timestep.
        conflict = is_conflict((0, 1), 1, (0, 0), 0, existing_paths)
        self.assertTrue(conflict)

    def test_sipp_pathfinding(self):
        # Verifies if the SIPP (Safe Interval Path Planning) algorithm can find a valid path from a start to a target location.
        # This ensures that the pathfinding mechanism works correctly and the agent is able to reach its goal.
        path = sipp((0, 0), (2, 2), self.rail, self.max_timestep, [], Directions.EAST)
        self.assertTrue(path)  # Ensure a valid path is found
        self.assertEqual(path[-1], (2, 2))  # Ensure the final position in the path is the target (2,2)

    def test_handle_movement_sipp(self):
        # Ensures that valid movement options are generated by the handle_movement_sipp function.
        # This checks if the function can correctly expand the state space for the agent and push potential movements into the open list.
        open_list = []
        path = []
        handle_movement_sipp((0, 0), 0, (5, 5), path, open_list, self.rail, [], Directions.EAST)
        
        # Ensures that movement options were correctly added to the open list
        self.assertGreater(len(open_list), 0)

    def test_relaxed_planning(self):
        # Verifies that the relaxed planning mechanism properly plans paths for only a subset of agents initially.
        # This is important for managing resource-constrained environments where not all agents' paths can be planned at once.
        path_compendium, pending_agents = relaxed_planning(self.agents, self.rail, self.max_timestep, self.initial_planning_fraction)
        
        self.assertEqual(len(path_compendium), 2)  # Two agents should have paths in the path compendium
        self.assertTrue(path_compendium[0])  # The first agent should have a planned path
        self.assertFalse(path_compendium[1])  # The second agent should still be pending for future planning

    def test_execute_with_relaxed_planning(self):
        # Tests the full execution of relaxed planning, ensuring that all agents eventually get valid paths.
        # This is critical to verify that the system works as expected under the partial initial planning paradigm.
        final_paths = execute_with_relaxed_planning(self.agents, self.rail, self.max_timestep, self.initial_planning_fraction)
        
        self.assertEqual(len(final_paths), 2)  # Ensure paths are generated for both agents
        self.assertTrue(final_paths[0])  # First agent should have a complete path
        self.assertTrue(final_paths[1])  # Second agent should have a complete path


if __name__ == '__main__':
    unittest.main(verbosity=2)