import unittest
from io import StringIO
import sys
from unittest.mock import patch
from ideal_completion import simulate_spin_hamiltonian  # Import the function

class TestSpinHamiltonian(unittest.TestCase):
    
    def setUp(self):
        """Redirect stdout to capture print outputs for verification."""
        # Set up a StringIO object to capture the standard output,
        # allowing us to verify print statements generated by the function.
        self.captured_output = StringIO()
        sys.stdout = self.captured_output

    def tearDown(self):
        """Reset stdout to its default value after each test."""
        # Reset stdout to its original setting to avoid interference with other tests or output.
        sys.stdout = sys.__stdout__

    @patch("matplotlib.pyplot.show")  # Patch plt.show to prevent plot from displaying
    def test_default_parameters(self, mock_show):
        """Test the function with default parameters."""
        # Verify that the function executes with default parameters (N=2, B=4.5, phi_deg=30).
        # This test checks if the function produces the expected printed output
        # and generates a plot, without displaying it, ensuring basic functionality.
        simulate_spin_hamiltonian()  # Run with default N=2, B=4.5, phi_deg=30
        output = self.captured_output.getvalue()
        
        # Check that the Zeeman frequency calculation is printed in MHz, which is critical
        # to ensure that the magnetic field and g-factor calculations are correct.
        self.assertIn("Electron Zeeman frequency:", output)
        self.assertIn("MHz", output)
        
        # Ensure that the plot was created and attempted to display without actually showing it.
        mock_show.assert_called_once()

    @patch("matplotlib.pyplot.show")  # Patch plt.show to prevent plot from displaying
    def test_increased_nuclear_spins(self, mock_show):
        """Test the function with an increased number of nuclear spins."""
        # Test with N=3 to check if the function can handle more nuclear spins.
        # This is important because increasing the number of spins increases the complexity
        # of the Hamiltonian, and the test verifies that the function scales correctly.
        simulate_spin_hamiltonian(N=3, B=4.5, phi_deg=30)
        output = self.captured_output.getvalue()
        
        # Check that the Zeeman frequency is printed, confirming that the function
        # executes correctly with a higher number of nuclear spins.
        self.assertIn("Electron Zeeman frequency:", output)
        self.assertIn("MHz", output)
        
        # Verify that the function attempts to display the plot.
        mock_show.assert_called_once()

    @patch("matplotlib.pyplot.show")  # Patch plt.show to prevent plot from displaying
    def test_altered_magnetic_field(self, mock_show):
        """Test the function with a higher magnetic field strength."""
        # Test with B=9.0 to verify that the function calculates the Zeeman frequency correctly
        # with a higher magnetic field strength, which is important for flexibility
        # in different experimental setups.
        simulate_spin_hamiltonian(N=2, B=9.0, phi_deg=30)
        output = self.captured_output.getvalue()
        
        # The test ensures the Zeeman frequency output reflects the stronger magnetic field,
        # confirming that the frequency calculation is responsive to magnetic field changes.
        self.assertIn("Electron Zeeman frequency:", output)
        self.assertIn("MHz", output)
        
        # Check that the plot was generated.
        mock_show.assert_called_once()

    @patch("matplotlib.pyplot.show")  # Patch plt.show to prevent plot from displaying
    def test_different_tilt_angle(self, mock_show):
        """Test the function with a different tilt angle."""
        # Test with phi_deg=45 to ensure the function can handle different tilt angles.
        # This is crucial because the tilt angle affects the spin dynamics, so this test
        # verifies that the function adapts to angle variations.
        simulate_spin_hamiltonian(N=2, B=4.5, phi_deg=45)
        output = self.captured_output.getvalue()
        
        # Check that the Zeeman frequency is printed, indicating that the function processes
        # the tilt angle correctly and reflects it in the calculation.
        self.assertIn("Electron Zeeman frequency:", output)
        self.assertIn("MHz", output)
        
        # Confirm that the plot was created as expected.
        mock_show.assert_called_once()

# Run the tests
if __name__ == "__main__":
    unittest.main(verbosity=2)